use_frameworks!

platform :ios, '10.0'

target 'LeaoPodLogger_Example' do
  pod 'LeaoPodLogger', :path => '../'

  target 'LeaoPodLogger_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
  end
end
